services:
  - type: web
    name: fraud-detection-chatbot
    env: python
    runtime: python-3.10.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: DEBUG
        value: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health